# Use .zprofile for login-time configuration, such as user environment setups like PATH modifications
#
# See .zshenv or .local/bin/env for universal settings and base environment variables required by non-interactive tasks
# or child processes

export PATH="$HOME/.local/bin:$PATH"

if [[ "$(uname)" == "Darwin" ]]; then
  # Added by OrbStack: command-line tools and integration
  # This won't be added again if you remove it.
  source ~/.orbstack/shell/init.zsh 2>/dev/null || :
fi

# Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
