#
# History
#
HISTFILE="$HOME/.zsh_history"
HISTSIZE=500000
SAVEHIST=500000

setopt appendhistory       # Append history to the file (don't overwrite)
setopt INC_APPEND_HISTORY  # Write history to the file immediately after each command
setopt SHARE_HISTORY       # Share history among all sessions
setopt EXTENDED_HISTORY

histsearch() { fc -lim "*$@*" 1 }
hs() { fc -lim "*$@*" 1 }

# Fix auto-complete for 'make' so that it works on Mac
zstyle ':completion:*:*:make:*' tag-order 'targets'
autoload -U compinit && compinit

#
# Aliases
#
alias git_files_status="git status | grep modified | sed -e 's/.*modified:   //g' | xargs echo"
alias git_files_origin_diff="git diff --compact-summary origin | awk '{print \$1}' | head -n -1 | xargs echo"
alias git_files_conflicts="git diff --name-only --diff-filter=U | awk '{print \$1}' | head -n -1 | xargs echo"
alias git_files_uncommitted="git diff --name-only"

#
# General Functions
#

# Run ssh-add on the specified file (arg 1) in $HOME/ssh/ otherwise guess at one.
function ssh_init() {
  local SSH_DIR="$HOME/.ssh"
  local MOST_RECENT_W_NO_EXT=$(for f in $SSH_DIR/*(D.om); do grep -q "PRIVATE" "$f" && { print -l "$f"; break }; done)
  if [[ $(ssh-add -L) == *identities* ]]; then
    if [[ -n "$1" && -f "$SSH_DIR/$1" && -r "$SSH_DIR/$1" ]]; then
      ssh-add $SSH_DIR/$1
    elif [[ -s "$SSH_DIR/id_ed25519" ]]; then
      ssh-add $SSH_DIR/id_ed25519
    elif [[ -s "$SSH_DIR/id_rsa" ]]; then
      ssh-add $SSH_DIR/id_rsa
    elif [[ -n "$MOST_RECENT_W_NO_EXTSSH_DIR" && -s "$MOST_RECENT_W_NO_EXTSSH_DIR" ]]; then
      ssh-add $MOST_RECENT_W_NO_EXTSSH_DIR
    else 
      echo "Specify the file in private key file $SSH_DIR/ that should be used with ssh-add."
    fi
  else
    printf echo "\nLooks like the ssh-agent already has a key.\n$(ssh-add -L)\n"
  fi
}

# Uses ripgrep (https://github.com/burntsushi/ripgrep) to replace
# the first arg with the second.
function smart_replace() {
  # See types with rg --type-list
  # Note that this relies on some types defined in ripgreprc
  rg -t cpp -t rust -t csharp -t py -t zig -t go -t java \
     -t sh -t cmd -t sql -t typescript -t web -t sass \
     -t bazel -t cmake -t tf -t jenkins -t cuda -t sip -t cppextra \
     -t txt -t readme -t json -t yaml -t toml -t xml -t markdown \
     --glob '!third_party*' \
     --files -0 |
    while IFS= read -r -d '' file; do
      echo "$file"
      sed -b -i -r ":1;/$1/I!b;s//\n&&&\n$2\n/;:2
          s/\n[[:lower:]](.*\n)(.)(.*\n)/\l\2\n\1\3/
          s/\n[^[:lower:]](.*\n)(.)(.*\n)/\u\2\n\1\3/;t2
          s/\n.*\n(.*)\n/\1/g;b1" "$file"
    done
}

function dumb_replace() {
  rg -t cpp -t rust -t csharp -t py -t zig -t go -t java \
     -t sh -t cmd -t sql -t typescript -t web -t sass \
     -t bazel -t cmake -t tf -t jenkins -t cuda -t sip -t cppextra \
     -t txt -t readme -t json -t yaml -t toml -t xml -t markdown \
     --glob '!third_party*' \
     --files -0 |
    while IFS= read -r -d '' file; do
      echo "$file"
      sed -b -i "s/$1/$2/g" "$file"
    done
}

# Removes the prefix (arg 1) from all files in a directory (arg 2).
function remove_prefix_from_files() {
  local prefix="$1"
  local dir="${2:-.}" # Default to current directory if not provided

  if [[ -z "$prefix" ]]; then
    echo "Usage: remove_prefix_from_files <prefix> [directory]"
    return 1
  fi

  # Loop through files in the specified directory that start with the prefix
  for file in "$dir/$prefix"*; do
    # Check if the file actually exists and is a regular file
    if [[ -f "$file" ]]; then
      # Extract the new filename by removing the prefix
      local new_name="${file#"$dir/$prefix"}"
      # Move (rename) the file
      mv "$file" "$dir/$new_name"
      echo "Renamed '$file' to '$dir/$new_name'"
    fi
  done
}

#
# Neovim Functions
#
function nv {
  # Takes neovim arguments
  if [[ "$1" == "-h" ]]; then
    nvim --help
  elif [[ "$1" == "--help" ]]; then
    nvim --help
  else
    # On mac, using -- to separate neovide and neovim cli flags causes a new buffer to show rather than the first file
    # passed after.
    neovide --no-tabs --fork $@
  fi
}

function nv_git_conflicts() {
  nv $(git_files_conflicts)
}

function nv_git_uncommitted() {
  #nv $(git status | grep modified | sed -e 's/.*modified:   //g' | xargs echo)
  nv $(git_files_uncommitted)
}

function nv_git_origin_diff() {
  nv $(git_files_origin_diff)
}

function nv_rg() {
  # Open all files matching the regex using nv
  rg --no-ignore-messages -l -0 "$@" | xargs --null bash -i -c 'nv $@'
}

#
# Multi-repo Functions
#
function mrepo-git-pull {
  if [[ ! -d "$1" ]]; then
    echo "Must specify a directory as first arg."
    return
  fi
  # Runs git pull across all repos in passed in directory.
  # Optionally takes the name of the branch to checkout first as 2nd arg.
  for d in $1/*/.git; do
    r=$(dirname "$d")
    printf '\n=== %s ===\n' "$(basename "$r")"
    if [[ -n "$2" ]]; then
      git -C "$r" checkout "$2"
    fi
    git -C "$r" pull --ff-only
  done
}

function mrepo-git-status {
  if [[ ! -d "$1" ]]; then
    echo "Must specify a directory as first arg."
    return
  fi
  for d in $1/*/.git; do
    r=$(dirname "$d")
    pushd $r >/dev/null
    printf '\n=== %s ===\n' "$(basename "$r")"
    git status
    popd >/dev/null
  done
}

function mrepo-git-diff {
  if [[ ! -d "$1" ]]; then
    echo "Must specify a directory as first arg."
    return
  fi
  git_branch() {
    git symbolic-ref --short -q HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null
  }
  for d in $1/*/.git; do
    r=$(dirname "$d")
    pushd $r >/dev/null
    printf '\n=== %s ===\n' "$(basename "$r")"
    echo "branch: $(git_branch)"
    git diff --compact-summary origin
    popd >/dev/null
  done
}

#
# Oh-My-Posh Prompt (https://ohmyposh.dev/)
#
OMP_CONFIG=$HOME/.config/omp/default.omp.json
[ -s "$OMP_CONFIG" ] && eval "$(oh-my-posh init zsh --config $OMP_CONFIG)"

